spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-activiti?characterEncoding=utf8
    username: root
    password: br13jHH5H6
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  activiti:
    check-process-definitions: false
server:
<<<<<<< HEAD
  port: 0
=======
  port: 8081
>>>>>>> branch 'master' of https://github.com/holdbelief/workflow


  