spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-activiti?characterEncoding=utf8
    username: root
    password: br13jHH5H6
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application: 
    name: Activiti-rest
  activiti:
    check-process-definitions: false
    
server:
  port: 8083
  
  
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8082/eureka